# fly.toml app configuration file generated for medical-ai-agentic on 2025-07-08T10:42:10+05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'medical-ai-agentic'
primary_region = 'ord'

[build]

[deploy]
  strategy = 'rolling'
  release_command = "echo 'Application starting...'"

[env]
  PORT = '8001'
  PYTHONUNBUFFERED = '1'

[processes]
  app = 'python app.py'

# Volume mount disabled for initial deployment - add back later if needed
# [[mounts]]
#   source = 'medical_ai_storage'
#   destination = '/app/storage'
#   initial_size = '3gb'

[http_service]
  internal_port = 8001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 50
    soft_limit = 25

  [[http_service.checks]]
    interval = '30s'
    timeout = '10s'
    grace_period = '60s'
    method = 'get'
    path = '/health'
    protocol = 'http'
    tls_skip_verify = false

[[vm]]
  memory = '8gb'
  cpu_kind = 'shared'
  cpus = 2

[[metrics]]
  port = 9091
  path = '/metrics'
